### ISSUE TITLE
Request a small example of how to run gatk using lpmx

### ISSUE THREAD

**Issue by xiekunwhy** [JasonYangShadow/lpmx#35]
Hi,

I want to run gatk in a container, and tried lpmx like following, but failed finaly, would you please give an example of how to run gatk?

./lpmx docker download broadinstitute/gatk
./lpmx docker fastrun broadinstitute/gatk:latest "/gatk/gatk"
FATAL: kernel too old

Best,
Kun

**Comment by JasonYangShadow** [comment]
@xiekunwhy sorry for the late reply. It usually means that your kernel version is too old( this error is reported by glibc, because lpmx(fakechroot) wraps glibc functions). 

You can try using vagrant(VMs) to run some composability experiments shown here
https://github.com/JasonYangShadow/experiment_attachments

For example, there are gatk3/gatk4 examples in this test script.(these test scripts are already included inside the VMs)
https://github.com/JasonYangShadow/experiment_attachments/blob/master/composability.sh

Hope that this reply can help you to some extent.

**Comment by xiekunwhy** [comment]
Thank for your reply, I will try VMs.
